#!/usr/bin/bash

scp nfb1@frankenstein.cmpgroup.ameslab.gov:'/home/nfb1/stevens-ml/TrainingData_D3h_4/TrainingData_D3h_4_1/generated_*_1000.csv /home/nfb1/stevens-ml/TrainingData_D3h_4/TrainingData_D3h_4_1/generated_*_2000.csv /home/nfb1/stevens-ml/TrainingData_D3h_4/TrainingData_D3h_4_1/*.npy /home/nfb1/stevens-ml/TrainingData_D3h_4/TrainingData_D3h_4_1/D3h_4_1_model.h5' .