#!/usr/bin/bash

scp nfb1@frankenstein.cmpgroup.ameslab.gov:'/home/nfb1/stevens-ml/TrainingData_C4v_4/TrainingData_C4v_4_-1/generated_*_1000.csv /home/nfb1/stevens-ml/TrainingData_C4v_4/TrainingData_C4v_4_-1/generated_*_2000.csv /home/nfb1/stevens-ml/TrainingData_C4v_4/TrainingData_C4v_4_-1/*.npy /home/nfb1/stevens-ml/TrainingData_C4v_4/TrainingData_C4v_4_-1/C4v_4_-1_model.h5' .